### ISSUE TITLE
Can't add multiple channels

### ISSUE THREAD

**Issue by orangelover** [dvdscripter/twitchegg#1]
I've tried adding multiple channels but I just can't figure it out

**Comment by dvdscripter** [comment]
You want to farm multiple channels? Right now you run multiple instances of the bot just changing the *farmchannel* and *channels* at json file.

If just want the bot to chill on multiple channels change json lines:

    "channels":[
    		"#channel1", "#channel2"
    	],

I'll start adding support for multiple farm on single instance.
